[settings]
Cookie = "__Host-postcrossing=f42092efaf6dae5453001d5ddf2aa6de; PostcrossingRemember=P3pdQ75bPVH87tR8oWRkdJoacpFAB5E5"
story_pic_type = "webp"

[url]
pic_driver_path = "https://pan.4a1801.life:11443/d/public/article/Arthur/Postcrossing_map_generator/gallery/picture"
story_pic_link = "https://pan.4a1801.life:11443/d/public/article/Arthur/Postcrossing_map_generator/template/content"
personal_page_link = "https://postcrossing.4a1801.life"

[notice]
db_update = false
