[settings]
Cookie = "__Host-postcrossing=4d4d27952b4c50aad75273301ddc41be; PostcrossingRemember=pEhVrgz4UXOKbJQc6PpHV0NysyPmguGO"
story_pic_type = "webp"

[url]
pic_driver_path = "https://pan.4a1801.life:11443/d/public/article/Arthur/Postcrossing_map_generator/gallery/picture"
story_pic_link = "https://pan.4a1801.life:11443/d/public/article/Arthur/Postcrossing_map_generator/template/content"
personal_page_link = "https://postcrossing.4a1801.life"

[notice]
db_update = false
